app.datasource.auth.url=jdbc:mariadb://localhost:3306/jobsearch_users?createDatabaseIfNotExist=true
app.datasource.auth.username=your_db_user
app.datasource.auth.password=your_db_password
app.datasource.auth.driver-class-name=org.mariadb.jdbc.Driver

app.datasource.tenant.username=your_db_user
app.datasource.tenant.password=your_db_password
app.datasource.tenant.driver-class-name=org.mariadb.jdbc.Driver
app.datasource.tenant.base-url=jdbc:mariadb://localhost:3306/
