app.datasource.auth.url=jdbc:mariadb://localhost:3306/jobsearch_users?createDatabaseIfNotExist=true
app.datasource.auth.username=jobsearch_app
app.datasource.auth.password=App1sv3ry*Cool
app.datasource.auth.driver-class-name=org.mariadb.jdbc.Driver

app.datasource.tenant.username=jobsearch_app
app.datasource.tenant.password=App1sv3ry*Cool
app.datasource.tenant.driver-class-name=org.mariadb.jdbc.Driver
app.datasource.tenant.base-url=jdbc:mariadb://localhost:3306/