package info.kornhuber.jobsearch.enums;

public enum CommunicationStatus {
    ZUSAGE,
    ABSAGE,
    IN_REFERENZ,
    TERMINVEREINBARUNG,
    BEWORBEN,
    BEWERBUNG_AKTUALISIERT,
    NACHGEFRAGT,
    DATEN_AKTUALISIERT,
    INFORMATION_ERHALTEN,
    INFORMATION_GEGEBEN,
    FRAGE_GESTELLT,
    FRAGE_BEANTWORTET,
    NIEMAND_ERREICHT,
    NICHTS_ERREICHT,
    IST_FORTZUSETZEN,
    SONSTIGES,
    OFFEN
}
